# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool: aws-todoistclonedev-useast1-ubuntu

steps:
  # - script: bicep --version
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "ARMPipeline-conn"
      subscriptionId: "3de95c80-2fcb-4898-8383-bd6ea88a226c"
      action: "Create Or Update Resource Group"
      resourceGroupName: "myBicepRg"
      location: "Central US"
      templateLocation: "Linked artifact"
      csmFileLink: "./main.bicep"
      deploymentMode: "Incremental"
      deploymentName: "DeployPipelineTemplate"
